name: app04_timer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  flutter_picker: ^2.1.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true

  assets:
    - lib/assets/sounds/sound.mp3
